/**
 * @file      main.cpp
 * @author    Frik Olivier
 * @date      2024-06-13
 *
 */

#include <Arduino.h>
#include "../lib/LilyGo_AMOLED/LilyGo_AMOLED.h"
#include "../lib/LilyGo_AMOLED/LV_Helper.h"

#include "ui/ui.h" //path to squareline studio (SLS) export

// This object is the complete board object
// It contains the drivers for all sensors such as
//     display, touch, power
LilyGo_Class amoled;

void setup()
{
    Serial.begin(115200);

    // Initialize the AMOLED, LVGL, and SLS
    Serial.println("Graphics Initialize Starting...");
    // Auto Detect the LilyGo S3 AMOLED from three possible boards
    //     - 1.47 inch, 1.91 inch, 2.41 inch
    // and load the appropriate drivers for LVGL
    while (!amoled.begin())
    {
        Serial.println("The board model cannot be detected, please raise the Core Debug Level to an error");
        delay(1000);
    }
    // Register lvgl helper
    beginLvglHelper(amoled);
    // Start SLS lvgl in ui.c - this file is generated by SLS
    ui_init();
    Serial.println("Graphics Initialize Done!");

    // Insert your Set-up code here
}

void loop()
{
    // lvgl task handler must be called in the loop
    lv_task_handler();

    // Insert your loop code here
    delay(5);
}